[package]
name = "sqlx-postgres-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.209"
sqlx = { version = "0.8.1", features = ["postgres", "runtime-tokio"] }
tokio = { version = "1.40.0", features = ["full"] }
